#!/usr/bin/env bash
# Collects endpoints and keys for the hand-built Azure resources and writes them
# to src/.env.local (gitignored). Prints masked values only, so nothing secret
# lands in terminal scrollback.
#
# Usage: ./scripts/write-env.sh
#
# This exists because the project currently authenticates with keys: Contributor
# rights allow reading keys but not creating the role assignments that keyless
# managed-identity auth needs. When those roles arrive, delete the *_KEY lines
# and DefaultAzureCredential takes over.

set -euo pipefail

RG="${RG:-rg-nsk-erp-copilot}"
FOUNDRY="${FOUNDRY:-foundry-nsk-erp-copilot}"
PROJECT="${PROJECT:-erp-copilot}"
SEARCH="${SEARCH:-srch-nsk-erp-copilot}"
STORAGE="${STORAGE:-stnskerpcopilot}"
COSMOS="${COSMOS:-cosmos-nsk-erp-copilot}"
APPI="${APPI:-appi-nsk-erp-copilot}"

OUT="$(cd "$(dirname "$0")/.." && pwd)/src/.env.local"

mask() { local v="$1"; if [ ${#v} -gt 8 ]; then echo "${v:0:4}…${v: -4}"; else echo "****"; fi; }
need() { command -v "$1" >/dev/null || { echo "missing: $1" >&2; exit 1; }; }

need az

echo "Reading resource metadata from ${RG}..."

FOUNDRY_ENDPOINT=$(az cognitiveservices account show -n "$FOUNDRY" -g "$RG" --query properties.endpoint -o tsv)
FOUNDRY_KEY=$(az cognitiveservices account keys list -n "$FOUNDRY" -g "$RG" --query key1 -o tsv)

SEARCH_KEY=$(az search admin-key show --service-name "$SEARCH" -g "$RG" --query primaryKey -o tsv)

COSMOS_ENDPOINT=$(az cosmosdb show -n "$COSMOS" -g "$RG" --query documentEndpoint -o tsv)
COSMOS_KEY=$(az cosmosdb keys list -n "$COSMOS" -g "$RG" --query primaryMasterKey -o tsv)

STORAGE_KEY=$(az storage account keys list -n "$STORAGE" -g "$RG" --query "[0].value" -o tsv)

APPI_CONN=$(az monitor app-insights component show --app "$APPI" -g "$RG" --query connectionString -o tsv)

umask 077
cat > "$OUT" <<EOF
# Generated by scripts/write-env.sh — DO NOT COMMIT.
# Regenerate any time; never edit by hand.

# --- Microsoft Foundry ---
AZURE_FOUNDRY_ENDPOINT=$FOUNDRY_ENDPOINT
AZURE_FOUNDRY_KEY=$FOUNDRY_KEY
AZURE_FOUNDRY_PROJECT=$PROJECT
# Deployment names, not model names. Swapping the underlying model is a portal
# change as long as these stay put.
AZURE_CHAT_DEPLOYMENT=chat
AZURE_EMBEDDING_DEPLOYMENT=embeddings
AZURE_OPENAI_API_VERSION=2025-04-01-preview

# --- Azure AI Search ---
AZURE_SEARCH_ENDPOINT=https://$SEARCH.search.windows.net
AZURE_SEARCH_KEY=$SEARCH_KEY
AZURE_SEARCH_INDEX=erp-docs

# --- Blob Storage (indexer data source) ---
AZURE_STORAGE_ACCOUNT=$STORAGE
AZURE_STORAGE_KEY=$STORAGE_KEY
AZURE_STORAGE_CONTAINER=docs

# --- Cosmos DB ---
AZURE_COSMOS_ENDPOINT=$COSMOS_ENDPOINT
AZURE_COSMOS_KEY=$COSMOS_KEY
AZURE_COSMOS_DATABASE=copilot

# --- Observability ---
APPLICATIONINSIGHTS_CONNECTION_STRING=$APPI_CONN
EOF

echo
echo "Wrote $OUT (permissions 600)"
echo
printf '  %-32s %s\n' "AZURE_FOUNDRY_ENDPOINT" "$FOUNDRY_ENDPOINT"
printf '  %-32s %s\n' "AZURE_FOUNDRY_KEY" "$(mask "$FOUNDRY_KEY")"
printf '  %-32s %s\n' "AZURE_SEARCH_ENDPOINT" "https://$SEARCH.search.windows.net"
printf '  %-32s %s\n' "AZURE_SEARCH_KEY" "$(mask "$SEARCH_KEY")"
printf '  %-32s %s\n' "AZURE_COSMOS_ENDPOINT" "$COSMOS_ENDPOINT"
printf '  %-32s %s\n' "AZURE_COSMOS_KEY" "$(mask "$COSMOS_KEY")"
printf '  %-32s %s\n' "AZURE_STORAGE_KEY" "$(mask "$STORAGE_KEY")"
printf '  %-32s %s\n' "APPLICATIONINSIGHTS_CONNECTION_STRING" "$(mask "$APPI_CONN")"
